### ISSUE TITLE
Upgrade Emscripten

### ISSUE THREAD

**Issue by ddohler** [ddohler/gdal-js#25]
We currently pin to Emscripten 1.37.22; later versions introduce useful modifications to reduce code size, but also have many backwards incompatibilities. Emscripten should be upgraded to the latest release and then the examples tested to make sure they still work.

**Comment by jkae** [comment]
I recognize that this is either in progress or not actively being worked on, but I wanted to comment that GDAL itself entirely fails to compile with Emscripten 1.38.47 (whereas 1.38.30 still works).

```
In file included from gdalgridavx.cpp:34:
In file included from /mnt/c/Documents/git/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include/immintrin.h:28:
/mnt/c/Documents/git/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include/mmintrin.h:47:5: error: use of
      undeclared identifier '__builtin_ia32_emms'; did you mean '__builtin_isless'?
    __builtin_ia32_emms();
    ^
/mnt/c/Documents/git/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include/mmintrin.h:47:5: note:
      '__builtin_isless' declared here
/mnt/c/Documents/git/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include/mmintrin.h:47:25: error: too few
      arguments to function call, expected 2, have 0
    __builtin_ia32_emms();
                        ^
/mnt/c/Documents/git/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include/mmintrin.h:64:19: error: use of
      undeclared identifier '__builtin_ia32_vec_init_v2si'
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
                  ^
/mnt/c/Documents/git/emsdk/fastcomp/fastcomp/lib/clang/6.0.1/include/mmintrin.h:81:12: error: use of
      undeclared identifier '__builtin_ia32_vec_ext_v2si'
    return __builtin_ia32_vec_ext_v2si((__v2si)__m, 0);

...
```

Furthermore, whatever file-related method overrides GDAL creates (namely with `__mmem` and `ftruncate`) cannot be carried over from a 1.38.30-compiled library to a 1.38.47 project.

proj4 builds, however only with fastcomp and not the upstream compiler.

I was wondering if you had any input/advice on building for newer Emscripten versions, or if I should try newer GDAL versions alongside proj6.

**Comment by ddohler** [comment]
Thanks for sending this! You're correct that I haven't started working on this issue yet, so unfortunately I don't have much advice to offer, although I will say that I'm somewhat skeptical that switching to a newer version of GDAL will fix the compilation issues you're seeing. The only other "advice" I have is that whenever I start working on this, I'll probably upgrade Emscripten versions one at a time in order to be able to isolate which version of Emscripten caused a particular error, and then consult the Emscripten docs and changelog in order to try to determine what adjustments might be needed.

But I also would like to hear more details about what you're trying to do. One of the primary reasons that this issue hasn't been worked on yet is that the current compilation process has so far been good enough for the applications where this library has been used; most users [install the pre-compiled version from NPM](https://www.npmjs.com/package/gdal-js). I would be happy to see this library gain wider adoption, however, so if you could let me know your use case and why the current setup doesn't satisfy it, it could provide motivation to address this issue sooner. I would also be happy to review and work through a pull request if you feel that is something that you might be able to do.

**Comment by jkae** [comment]
I'm utilizing GDAL as a library within another WebAssembly app, so my primary interest is in compiling GDAL and PROJ so that I can link them (as emscripten's dynamic wasm linking is still a work-in-progress and doesn't seem to be sufficient for my needs regardless).

My use-case for gdal-js has been with the work you've already done in identifying what can be excluded from the build and how to utilize the emscripten toolchain in the very specific, correct way that's needed. I'd very much like to contribute to the project if I can help, though I'm almost at a loss of what to do.

**Comment by ddohler** [comment]
Got it, thanks. In that case, my best advice for you is to use GDAL 2.1 and an earlier version of Emscripten if you can. If there's a feature in a newer version of Emscripten that you absolutely need, then I would start with the latest version you can find that works, and then work your way forward, one point version at a time, and work through the issues as you go.

I'm sorry I can't be more helpful than that; I probably won't be able to get back to this project for a couple months, at the least. However, I can say that I have found the Emscripten community to be pretty helpful, so you might try asking questions there as well, especially if you can narrow things down to a particular version that breaks the GDAL build. https://emscripten.org/docs/introducing_emscripten/community.html

It sounds like you'll be doing most of your work in a different project and just consulting the code here for reference, so it makes sense to me that there wouldn't be any pull requests coming out of that work. However, if you do happen to find something that could be applicable here, please consider putting together a PR.

Good luck!

**Comment by ddohler** [comment]
@jkae Apologies for taking so long to get back to you, but as of March, gdal-js is on Emscripten 1.39.2, which was the latest version of Emscripten at the time. It may be too late for this to be of use to you, but I wanted to let you know in case it isn't.
